apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
spec:
  replicas: 0
  selector:
    matchLabels:
      app: nginx
      environment: dev 
  template:
    metadata:
      labels: 
        app: nginx
        environment: dev
    spec:
      volumes: 
      - name: volume
        hostPath:
          path: /mnt/data

      containers:
      - name: container-nginx
        image: nginx
        volumeMounts:
         - name: volume
           mountPath: "/var/nginx-data"
